
export STARPU_CFLAGS := $(shell pkg-config --cflags starpu-1.4)
export STARPU_LDLIBS := $(shell pkg-config --libs starpu-1.4)

CFLAGS := $(STARPU_CFLAGS) -Wall -fopenmp
LDLIBS += $(STARPU_LDLIBS) -lm -lc 

# the compiler writes objs/*.d files listing the project headers each object includes, so that
# editing a header rebuilds the objects that depend on it (-MP: no error if a header is removed)
DEPFLAGS = -MMD -MP

ifeq ($(RELEASE_MODE), 1)
	CFLAGS += -O3 -DRELEASE
else
	CFLAGS += -O0 -g
endif

ifeq ($(NO_CPU_KERNEL), 1)
	CFLAGS += -DNO_CPU_KERNEL
endif

# bit-exact CPU vs GPU validation: no fused multiply-add on either side (on aarch64 gcc fuses by
# default; on x86-64 without -march it doesn't, so there this changes nothing)
ifeq ($(EXACT_FP), 1)
	CFLAGS += -ffp-contract=off
endif

export PARENT_DIR := $(CURDIR)

BIN = main

SRCDIR = src
OBJDIR = objs
RESDIR = results
DERIVATIVESDIR = $(SRCDIR)/derivatives
export INCLUDEDIR = src/includes

# generated by cross-deriv-gen.py, included by derivatives-impl.h
CROSS_DERIV_GEN = $(DERIVATIVESDIR)/cross-deriv.gen.c

SRCS_ = argparse.c derivatives.c kernel.c main.c medium.c mem.c vector.c io.c partition.c
SRCS := $(addprefix $(SRCDIR)/, $(SRCS_))
OBJS := $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o,$(SRCS))

CUDADIR = $(SRCDIR)/cuda
CUDAOBJS = $(OBJDIR)/cuda_kernel.o
ifeq ($(CUDA_BACKEND), 1)
    CFLAGS += -DCUDA_BACKEND
    OBJS += $(CUDAOBJS)
    LDLIBS += -lcudart -lstdc++

    NVCC = nvcc
    NVCCFLAGS = $(STARPU_CFLAGS) -arch=$(ARCH)

    ifeq ($(RELEASE_MODE), 1)
	    NVCCFLAGS += -O2
    else
	    NVCCFLAGS += -O0 -g
    endif

    ifeq ($(EXACT_FP), 1)
	    NVCCFLAGS += -fmad=false
    endif
endif

ARGS = TTI 200 200 200 8 12.5 12.5 12.5 0.0001 0.001 4 0.0005

.PHONY: all clean run print test debug valgrind lsp

all: $(BIN)

$(BIN): $(OBJS)
	$(CC) $(CFLAGS) $(LDLIBS) $^ -o $@


# the generated cross derivatives are only regenerated when the generator changes
$(CROSS_DERIV_GEN): $(DERIVATIVESDIR)/cross-deriv-gen.py
	python3 $< > $@

$(OBJDIR)/derivatives.o: $(CROSS_DERIV_GEN)

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) $(DEPFLAGS) -c $< -o $@ -I $(INCLUDEDIR)

$(OBJDIR)/cuda_kernel.o: $(CUDADIR)/kernel.cu $(SRCDIR)/derivatives/derivatives-impl.h $(INCLUDEDIR)/wave-neighborhood.h $(CROSS_DERIV_GEN)
	@mkdir -p $(OBJDIR)
	$(NVCC) $(NVCCFLAGS) -c $< -o $@ -I $(INCLUDEDIR)

# header dependencies written by -MMD (missing on the first build, which compiles everything anyway)
-include $(OBJS:.o=.d)


run: $(BIN)
	@mkdir -p $(RESDIR)
	@echo "Runing $(BIN). Out putting at ./$(RESDIR)"
	./$(BIN) $(ARGS)

debug: $(BIN)
	@mkdir -p $(RESDIR)
	gdb --args ./$(BIN) $(ARGS)

lsp:
	bear -- make clean all

valgrind: $(BIN)
	@mkdir -p $(RESDIR)
	valgrind ./$(BIN) TTI 16 16 16 4 12.5 12.5 12.5 0.001 0.1 2 0.01

print:
	@echo "Sources: $(SRCS)"
	@echo "Objects: $(OBJS)"

# need to pass the commands directly inline
test: $(CROSS_DERIV_GEN)
	$(MAKE) -C tests 

clean:
	rm -f $(BIN) $(OBJS) $(CUDAOBJS) $(OBJS:.o=.d)
